### ISSUE TITLE
different credential environment variables

### ISSUE THREAD

**Issue by eyalto** [allegroai/trains-pycharm-plugin#1]
in trains-server user credential can be exported as:

```
export TRAINS_API_ACCESS_KEY=""
export TRAINS_API_SECRET_KEY=""
export TRAINS_API_HOST=""

```

in the plugin the os.environ report other env names for the same things:

`
'ALG_API_ACCESS_KEY'
'ALG_API_SECRET_KEY'
'ALG_API_HOST'
`

**Comment by allegroai-git** [comment]
They are interchangeable e.g.  TRAINS_API_ACCESS_KEY or ALG_API_ACCESS_KEY are both valid.
