### ISSUE TITLE
Pycharm plugin git inspection through remote run doesn't work in Pycharm 2021.2.1

### ISSUE THREAD

**Issue by nitzanwsc** [allegroai/trains-pycharm-plugin#3]
Pycharm Build 212.5080.64 on windows 11 (os build 22000.318).
Remote execution through ssh on azure VM with mapping my code from git folder to temp folder.
In this environment ClearML treats my code as standalone script and not inspecting all the files in the project.

**Comment by bmartinn** [comment]
Hi @nitzanwsc 
I was not able to reproduce this behavior ...
I tested on Windows 10 w/ `PyCharm 2021.2.3` and `ClearML-PyCharm-plugin v1.0.1` everything worked as expected.
Could it be that `git` is not in the default Windows PATH ?
Can you add a print in the remote session (i.e. just when the code starts, and executed on the SSHed remote machine)?

```python
import os
print('CLEARML_VCS_REPO_URL', os.environ.get('CLEARML_VCS_REPO_URL'))
```

**Comment by nitzanwsc** [comment]
It prints None.
What do you mean by default path? It sits under C:\Program Files\Git\cmd and I have this path in my PATH env.

**Comment by nitzanwsc** [comment]
@JDennisJ and I found the problem (we think...)
When running the code with "Run with python console" the plugin is not working (specifically cannot find the repository).
